### ISSUE TITLE
Reload required when adding new dependencies to package.yaml

### ISSUE THREAD

**Issue by ratherforky** [digital-asset/ghcide#155] opened 2019-10-06 11:38 UTC
When adding new dependencies to `package.yaml` you need to reload VSCode to keep ghcide up to date.

To reproduce:

- Add a new dependency to the `package.yaml` of a project
- Import a module from that new dependency
- You get an error for the import
- Reload and the error should go away

Adding a new dependency happens relatively infrequently so this isn't a big deal, but I thought it might be worth noting as a limitation if it isn't easy to fix.

**Comment by cocreature** [comment] 2019-10-06 11:39
Thanks for the issue, this is a duplicate of #50 so I’m closing it.

**Closed by cocreature** 2019-10-06 11:39 UTC
