### ISSUE TITLE
ghcide does not seem to report non-exhaustive pattern matches as diagnostics

### ISSUE THREAD

**Issue by mitchellwrosen** [digital-asset/ghcide#130] opened 2019-09-25 00:33 UTC
I'm surprised there hasn't been an issue raised about this already, so I suspect my setup is to blame. `ghcide` does not seem to be reporting warnings such as:

```
src/Nng.hs:336:19: warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In a case alternative: Patterns not matched: _
    |
336 | addressFromText = \case
    |                   ^^^^^...
```

**Comment by cocreature** [comment] 2019-09-25 05:37
`-Wincomplete-patterns` is not enabled by default. Are you sure that your cradle enables it? E.g., if you use the stack or cabal cradles you need to enable it in your cabal file.

**Comment by ndmitchell** [comment] 2019-09-25 05:56
This is a dupe of https://github.com/digital-asset/ghcide/issues/107 which explains why it hapoens

**Comment by cocreature** [comment] 2019-09-25 06:44
Ah good point, thanks. I got confused because I was sure that I had seen this warning for DAML but of course we generate Core there. Closing as a duplicate.

**Closed by cocreature** 2019-09-25 06:44 UTC
Labels: duplicate
