### ISSUE TITLE
Upload a new release to Hackage

### ISSUE THREAD

**Issue by pepeiborra** [digital-asset/ghcide#595] opened 2020-06-01 15:54 UTC
There have been major improvements and new features since 0.1.0 was released a few months ago. Time for a new release?

**Comment by pepeiborra** [comment] 2020-06-01 15:56
I an happy to send a PR to update the change log if that helpd

**Comment by cocreature** [comment] 2020-06-01 18:17
I was planning to make a release after #522 has landed.

**Comment by ndmitchell** [comment] 2020-06-01 18:31
My guess is #522 is going to destabilise things for a bit? Another option (if releases are cheap) would be to a cut a release now, and then when #522 lands, wait a few weeks of internal testing from us until we release again.

**Comment by cocreature** [comment] 2020-06-01 18:33
I’d rather spot the issues caused by #522 quickly (if there are any :slightly_smiling_face:) and a release seems like the best option for that. And even with issues, this is probably one of if not the most requested feature recently so a lot of people will benefit from it.

**Comment by cocreature** [comment] 2020-06-02 15:18
0.2.0 is out

**Closed by cocreature** 2020-06-02 15:18 UTC
